name: Update Plugin Assets/Readme

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  assets_readme_update:
    name: Update Assets/Readme
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: smartpay
          ASSETS_DIR: .wordpress-org
          README_NAME: readme.txt
          IGNORE_OTHER_FILES: true
